### ISSUE TITLE
[BackEnd] CRUD video

### ISSUE THREAD

**Issue by LuisAcostaSicilia** [OscarArnedo/LS2-protube-grup9#33]
Adaptar el CRUD de video a la BD

**Comment by LuisAcostaSicilia** [comment]
Al final no s'ha fet tot el CRUD sencer. S'ha fet:
- Un getVideos per mostrar els vídeos en la secció inicial.
- Dos vídeos DTO per la secció inicial i la futura pàgina de vídeo (un cop es seleccioni un vídeo).

S'ha de fer:
- El update de vídeo un cop tinguem els users creats a la base de dades.
- La resta de endpoints necessaris.

**Comment by OscarArnedo** [comment]
Subtesques asociades:

- [x] #88 
- [x] #89 
- [x] #90
